name: Claude Code OAuth (simple-fast)

on:
  issue_comment:
    types: [created]

jobs:
  claude:
    # 「@claude」が入っている時だけ実行
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      issues:   write
      pull-requests: write
      contents: read

steps:
  - uses: actions/checkout@v4

  - uses: oven-sh/setup-bun@v2
    with:
      bun-version: 1.2.15          # 固定してキャッシュ安定
  - name: Install prod deps
    run: bun install --production  # ここまでで 4〜6 s

  - uses: hiromima/claude-code-action@main
    with:
      use_oauth: 'true'
      claude_access_token:  ${{ secrets.CLAUDE_ACCESS_TOKEN }}
      claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
      claude_expires_at:    ${{ secrets.CLAUDE_EXPIRES_AT }}

