name: Claude Code OAuth Fast
on:
  issue_comment:
    types: [created]

concurrency:
  group: claude-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  claude:
    if: ${{ contains(github.event.comment.body, '@claude') }}
    runs-on: ubuntu-latest
    env: { BUN_VERSION: 1.2.15 }

    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Bun 本体キャッシュ
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ env.BUN_VERSION }}-${{ hashFiles('bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      # Bun セットアップ（cache 入力は不要）
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      # node_modules キャッシュ
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package.json', 'bun.lockb') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Install prod deps
        run: bun install --production

      - uses: hiromima/claude-code-action@main
        with:
          use_oauth: 'true'
          claude_access_token:  ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at:    ${{ secrets.CLAUDE_EXPIRES_AT }}

